### PR TITLE
Dashboard Leaderboard

### PR DESCRIPTION
**Pull request by rizalarfiyan**
# Merge/Pull Request (PR)

**Title of PR** : *Dashboard Leaderboard*

**Type of PR** :

- [x] New Feature
- [ ] Bug Fix

**Main Point** :

- [ ] Integration
- [x] Use global component
- [x] Slicing
- [x] Dark Mode Support
- [x] Responsive
- [x] Code linter and format
- [x] Reusable code

**About the PR** :

- Create badge component
- Create alert component
- Create table component
- Create page dashboard leaderboard

**Preview (mobile and desktop)** :
dashboard leaderboard:
image

### CODE REVIEW

**Review by Ahmad-mufied — APPROVED** [review]

**Review by damar-glh — APPROVED** [review]
GGWP, JOS GANDOSS

**Comment by Wisnu-kusuma-dewa** [comment]
Ku mengerti arti cinta

**Review by glngnoor — APPROVED** [review]
👑👑👑

**Review by glngnoor — APPROVED** [review]
👑👑👑

**Comment by rizalarfiyan** [comment]
:laughing: Kocak Kocak :v

**Pull request merged**
